# Generated by Django 4.2.6 on 2023-10-30 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0005_alter_culturepost_options_alter_eventpost_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='', verbose_name='Файл')),
                ('culture_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.culturepost')),
                ('event_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.eventpost')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
