# Generated by Django 4.2.6 on 2023-11-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediacore', '0002_alter_imagefile_culture_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefile',
            name='culture_post',
        ),
    ]
