# Generated by Django 4.2.6 on 2023-11-09 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediacore', '0003_remove_imagefile_culture_post'),
        ('posts', '0009_historypost_alter_eventpost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='history_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.historypost'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='file',
            field=models.ImageField(upload_to='posts', verbose_name='Файл'),
        ),
    ]
