# Generated by Django 4.2.6 on 2023-10-26 19:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInURL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('from_date', models.DateField(verbose_name='Начало действия')),
                ('to_date', models.DateField(verbose_name='Конец действия')),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/', verbose_name='QR код')),
                ('reward_points', models.PositiveIntegerField(default=0, verbose_name='Очки вознаграждения')),
                ('enabled', models.BooleanField(default=True, verbose_name='Действует')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
