# Generated by Django 4.2.6 on 2023-11-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_travelroute_travelrouteday'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrouteday',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='travelrouteday',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
    ]
