# Generated by Django 4.2.6 on 2023-11-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_travelrouteday_comment_alter_travelrouteday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrouteday',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
