# Generated by Django 4.2.6 on 2023-11-07 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_alter_travelrouteday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelroute',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel', to=settings.AUTH_USER_MODEL),
        ),
    ]
