# Generated by Django 4.2.6 on 2023-11-10 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_travelroute_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardpointtransaction',
            name='check_in_url',
        ),
        migrations.RemoveField(
            model_name='rewardpointtransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='travelroute',
            name='user',
        ),
        migrations.RemoveField(
            model_name='travelrouteday',
            name='events',
        ),
        migrations.RemoveField(
            model_name='travelrouteday',
            name='route',
        ),
        migrations.DeleteModel(
            name='CheckInURL',
        ),
        migrations.DeleteModel(
            name='RewardPointTransaction',
        ),
        migrations.DeleteModel(
            name='TravelRoute',
        ),
        migrations.DeleteModel(
            name='TravelRouteDay',
        ),
    ]
