# Generated by Django 4.2.6 on 2023-10-25 20:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=400, verbose_name='Описание')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=400, verbose_name='Описание')),
                ('address', models.CharField(max_length=100, verbose_name='Адррес')),
                ('is_unlimited_working_time', models.BooleanField(verbose_name='Время работы неограничено')),
                ('working_time_start', models.DateTimeField(blank=True, null=True, verbose_name='Время работы(начало)')),
                ('working_time_end', models.DateTimeField(blank=True, null=True, verbose_name='Время работы(конец)')),
                ('is_unlimited_event_time', models.BooleanField(verbose_name='Время проведения неограничено')),
                ('event_time_start', models.DateTimeField(blank=True, null=True, verbose_name='Период проведения(начало)')),
                ('event_time_end', models.DateTimeField(blank=True, null=True, verbose_name='Период проведения(конец)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckInURL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('from_data', models.DateField(verbose_name='Начало действия')),
                ('to_date', models.DateField(verbose_name='Конец действия')),
                ('qr_code', models.ImageField(blank=True, upload_to='', verbose_name='QR код')),
                ('reward_points', models.PositiveIntegerField(default=0, verbose_name='Очки вознаграждения')),
                ('enabled', models.BooleanField(default=True, verbose_name='Действует')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
