# Generated by Django 4.2.6 on 2023-10-25 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkinurl',
            old_name='from_data',
            new_name='from_date',
        ),
    ]
