# Generated by Django 4.2.6 on 2023-10-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_from_data_checkinurl_from_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckInURL',
        ),
    ]
