# Generated by Django 4.2.6 on 2023-11-10 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_historypost_next_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historypost',
            old_name='centuary',
            new_name='century',
        ),
    ]
